kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kubernetesVersion: v1.16.15
    kind: ClusterConfiguration
    apiServer:
      certSANs:
        - "host.docker.internal"
        - "127.0.0.1"
        - "172.17.0.1"
      extraArgs:
        feature-gates: SCTPSupport=true
    ---
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    mode: ipvs
    ---
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: MasterConfiguration
    apiServerCertSANs:
    - host.docker.internal
